name: Upload Firmware on Master Update

on:
  push:
    branches:
      - master

jobs:
  upload-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Get Latest Firmware
      id: get_latest_firmware
      run: |
        latest_file=$(ls -t esp/firmware/* | head -n 1)
        echo "latest_file=$latest_file" >> $GITHUB_ENV

    - name: Upload to Firebase Storage
      env:
        FIREBASE_TOKEN: yyum6rEl2HQQqcy8ePZUQbBHmYPR7sHsrDXHkbCI
        STORAGE_URL: leef-46909.appspot.com
      run: |
        latest_file="${{ env.latest_file }}"
        gsutil cp "$latest_file" "gs://leef-46909.appspot.com/firmware/$(basename $latest_file)"

    - name: Update Firebase Realtime Database
      env:
        FIREBASE_TOKEN: yyum6rEl2HQQqcy8ePZUQbBHmYPR7sHsrDXHkbCI
        DATABASE_URL: https://leef-46909-default-rtdb.firebaseio.com/
      run: |
        latest_file="${{ env.latest_file }}"
        filename=$(basename "$latest_file")
        upload_date=$(date +"%Y-%m-%d %H:%M:%S")
        file_url="https://storage.googleapis.com/leef-46909.appspot.com/firmware/$filename"
        firebase database:update --data "{ \"dateUploaded\": \"$upload_date\", \"filename\": \"$filename\", \"url\": \"$file_url\" }" "https://leef-46909-default-rtdb.firebaseio.com/firmware/$filename.json"
