name: Upload Firmware on Master Update

on:
  push:
    branches:
      - master

jobs:
  upload-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm install -g firebase-tools
        npm install firebase-admin

    - name: Get Latest Firmware
      id: get_latest_firmware
      run: |
        latest_file=$(ls -t esp/firmware/* | head -n 1)
        echo "latest_file=$latest_file" >> $GITHUB_ENV

    - name: Upload to Firebase Storage
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT}" > firebase-service-account.json
        node <<EOF
        const admin = require('firebase-admin');
        const serviceAccount = require('./firebase-service-account.json');
        admin.initializeApp({
          credential: admin.credential.cert(serviceAccount),
          storageBucket: process.env.STORAGE_URL
        });
        const { Storage } = require('@google-cloud/storage');
        const storage = new Storage();
        const bucket = storage.bucket(process.env.STORAGE_URL);
        const path = '${{ env.latest_file }}';
        const destFileName = 'firmware/' + path.split('/').pop();
        bucket.upload(path, { destination: destFileName })
          .then(() => console.log('File uploaded successfully'))
          .catch(err => console.error('ERROR:', err));
        EOF

    - name: Update Firebase Realtime Database
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT}" > firebase-service-account.json
        node <<EOF
        const admin = require('firebase-admin');
        const serviceAccount = require('./firebase-service-account.json');
        admin.initializeApp({
          credential: admin.credential.cert(serviceAccount),
          databaseURL: process.env.REALTIME_DATABASE_URL
        });
        const db = admin.database();
        const ref = db.ref('firmware');
        const path = '${{ env.latest_file }}';
        const filename = path.split('/').pop();
        const uploadDate = new Date().toISOString();
        const fileUrl = `https://storage.googleapis.com/${process.env.STORAGE_URL}/firmware/${filename}`;
        ref.child(filename.replace(/\./g, '_')).set({
          dateUploaded: uploadDate,
          filename: filename,
          url: fileUrl
        }, (error) => {
          if (error) {
            console.error('Error updating database:', error);
          } else {
            console.log('Database updated successfully');
          }
        });
        EOF
